### ISSUE TITLE
Feature Request:  Support MySQL collate utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by zmoon460** [oceanbase/oceanbase#1403]
Hi：
My application uses MySQL COLLATE utf8mb4_ unicode_ci  ,  Oceanabase only supports utf8mb4_ general_ ci,   increase support for utf8mb4_ unicode_ci   ?

**Comment by caifeizhi** [comment]
Thank you for your feedback! May I ask if you could provide more details:
1. whether it can be avoided in the application
2. and if not, what are the main reason

This information can help us better understand this requirement.

**Comment by CamberLoid** [comment]
Same feat. request for my case and I might be able to provide an application name: Grafana. 

When I configure a newly-deployed Grafana to connect our OB Community instance it complain about unknown collation and refuse to continue. 

(Fixme: paste log here)

Grafana's configuration storage requires a MySQL/PostgreSQL to achieve HA design. However it hardcoded utf8mb4-unicode-ci into its source, and so far another feature request for Grafana to make its collation customizable is opened but no progress. So there is no way to avoid it unless we modify & re-build Grafana from source (and even impossible for its enterprise distribution, but luckily my case uses OSS edition) and see if we are lucky enough.

(Fixme: paste grafana's code here)

And so far I haven't tried to maintain our Grafana's source code. Haven't tried OB Enterprise yet because a different problem occurs when connecting but it would be off-topic discussing here.

**Comment by wub** [comment]
We have the same request here. Specifically, it would be great to have:

* `utf8mb4_ unicode_ci`
* `utf8mb4_0900_ai_ci`
* `utf8mb4_unicode_520_ci`

Sometimes we can get around the issue by changing code, or introducing interceptors that rewrite the collation on the fly, but that's obviously not a sustainable or stable solution.

**Comment by wub** [comment]
It looks like this will be supported in OceanBase 4.2.2: https://github.com/orgs/oceanbase/projects/4/views/5?pane=issue&itemId=29577744
