### ISSUE TITLE
[Bug]: obshell not found

### ISSUE THREAD

**Issue by ysj1173886760** [oceanbase/oceanbase#1829]
**Describe the bug**

找不到OBShell。尝试使用 `wget http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm`也报错NotFound

**Environment**

- OS Version and CPU Arch(`uname -a`):

Debian10
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):

**Fast Reproduce Steps(Required)**

clone oceanbase and install dependencies.

then run: 
bash build.sh debug --init --make

**Expected behavior**

compile normally.

**Actual Behavior**

reported an error. said `http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm` not found

**Additional context**

change obshell version from 32024010810 to 102024011512 works fine here.

**Comment by hnwyllmm** [comment]
问题已收到。假期结束我们会及时修复。可以先在deps目录下把obshell相关的内容删除然后重新编译。发自我的 iPhone在 2024年2月9日，10:16，sheep ***@***.***> 写道：﻿
Describe the bug

找不到OBShell。尝试使用 wget http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm也报错NotFound
Environment


OS Version and CPU Arch(uname -a):

Debian10

OB Version(LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V):

Fast Reproduce Steps(Required)
Steps to reproduce the behavior:
clone oceanbase and install dependencies.
then run:
bash build.sh debug --init --make
Expected behavior

compile normally.
Actual Behavior

reported an error. said http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm not found
Additional context

change obshell version from 32024010810 to 102024011512 works fine here.

**Comment by ysj1173886760** [comment]
> 问题已收到。假期结束我们会及时修复。可以先在deps目录下把obshell相关的内容删除然后重新编译。发自我的 iPhone在 2024年2月9日，10:16，sheep ***@***.***> 写道：﻿ Describe the bug 找不到OBShell。尝试使用 wget [http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm也报错NotFound](http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm%E4%B9%9F%E6%8A%A5%E9%94%99NotFound) Environment OS Version and CPU Arch(uname -a): Debian10 OB Version(LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V): Fast Reproduce Steps(Required) Steps to reproduce the behavior: clone oceanbase and install dependencies. then run: bash build.sh debug --init --make Expected behavior compile normally. Actual Behavior reported an error. said http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm not found Additional context change obshell version from 32024010810 to 102024011512 works fine here. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

删除掉obshell的就可以吗，改成102024011512是不是更好点。这两个版本区分有什么用意吗

**Comment by hnwyllmm** [comment]
我现在无法确定。obshell对整体代码并没有影响，所以你修改版本也没有问题。后面我们会发布正确的文件。发自我的 iPhone在 2024年2月9日，10:34，sheep ***@***.***> 写道：﻿

问题已收到。假期结束我们会及时修复。可以先在deps目录下把obshell相关的内容删除然后重新编译。发自我的 iPhone在 2024年2月9日，10:16，sheep @.> 写道：﻿ Describe the bug 找不到OBShell。尝试使用 wget http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm也报错NotFound Environment OS Version and CPU Arch(uname -a): Debian10 OB Version(LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V): Fast Reproduce Steps(Required) Steps to reproduce the behavior: clone oceanbase and install dependencies. then run: bash build.sh debug --init --make Expected behavior compile normally. Actual Behavior reported an error. said http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm not found Additional context change obshell version from 32024010810 to 102024011512 works fine here. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

删除掉obshell的就可以吗，改成102024011512是不是更好点。这两个版本区分有什么用意吗

**Comment by ysj1173886760** [comment]
> 我现在无法确定。obshell对整体代码并没有影响，所以你修改版本也没有问题。后面我们会发布正确的文件。发自我的 iPhone在 2024年2月9日，10:34，sheep ***@***.***> 写道：﻿ 问题已收到。假期结束我们会及时修复。可以先在deps目录下把obshell相关的内容删除然后重新编译。发自我的 iPhone在 2024年2月9日，10:16，sheep @.> 写道：﻿ Describe the bug 找不到OBShell。尝试使用 wget [http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm也报错NotFound](http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm%E4%B9%9F%E6%8A%A5%E9%94%99NotFound) Environment OS Version and CPU Arch(uname -a): Debian10 OB Version(LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V): Fast Reproduce Steps(Required) Steps to reproduce the behavior: clone oceanbase and install dependencies. then run: bash build.sh debug --init --make Expected behavior compile normally. Actual Behavior reported an error. said http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64//obshell-4.2.2.0-32024010810.el7.x86_64.rpm not found Additional context change obshell version from 32024010810 to 102024011512 works fine here. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.> 删除掉obshell的就可以吗，改成102024011512是不是更好点。这两个版本区分有什么用意吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

好的，感谢大佬

**Comment by hnwyllmm** [comment]
This issue was fixed.

**Comment by ysj1173886760** [comment]
> This issue was fixed.

cool. thanks a lot
