### ISSUE TITLE
Please STOP star purchase

### ISSUE THREAD

**Issue by gao-sun** [oceanbase/oceanbase#422]
It's really embarrassing to purchase GitHub stars in disguise over social networks. It means nothing to the project but pollutes the community, which significantly reduces the credibility of the star number.

For the courtesy, I won't post any screenshots or other proofs here. But, please, STOP doing it.

Thank you.

**Comment by tikazyq** [comment]
I don't think a good open source project will need to be promoted through some so-called marketing campaigns. This is absolutely an unethical action in open source communities, which I believe some the admin team of this open source project has gone too far. If you really wanna promote your project and make contributions to the community, please DO NOT play tricks and fool developers with the valueless toys and gifts. It will be in vain you attempt to transfer your business knowledge in your commercial environment here, because our developers will not be attracted by your tricks. Please be reminded that a success open source project does not need hard marketing promotions. Hope you can gain some hard learnings from this mistake. Good luck!

**Comment by labulaka521** [comment]
![image](https://user-images.githubusercontent.com/24547356/138618597-985ef602-dbfd-415d-944d-b03fbe3a8a16.jpeg)![image](https://user-images.githubusercontent.com/24547356/138618601-a99771d6-3e52-4980-a4bb-7e90a87c86c3.jpeg)

fake project！

**Comment by zdrjson** [comment]
> 

sss
