### ISSUE TITLE
Please add some comments

### ISSUE THREAD

**Issue by junfx** [oceanbase/oceanbase#6]
Where has the comments gone?

**Comment by junfx** [comment]
And the commits history?

**Comment by raywill** [comment]
I believe that they decided not to disclose the commits history for security reason.

Since OceanBase have grown for more than ten years internally, the commit logs should have too many sensitive information which is not suitable to disclose.

**Comment by yishenglanlingzui** [comment]
I wanted to find my name in the code, but in the end I gave up

**Comment by tabokie** [comment]
I understand the sensitivity of commit history. But still I don't think such a large codebase is readable at all without sufficient comments.

Since I observed a few codes are commented in English, maybe the other comments are removed simply because they are originally written in Chinese? If that's the case is there any plan to port them back? @LINxiansheng @MizuhaHimuraki
