### ISSUE TITLE
network 

### ISSUE THREAD

**Issue by liuqian1990** [oceanbase/oceanbase#722]
```
虚拟机网卡，无法取得值 
cat: /sys/class/net/eth0/speed: Invalid argument
[2021-12-21 21:47:38.970407] WARN  load_file_to_string (utility.h:545) [25455][2][Y0-0000000000000000] [lt=3] [dc=0] read /sys/class/net/eth0/speed failed, errno 22
[2021-12-21 21:47:38.970427] WARN  get_ethernet_speed (utility.cpp:619) [25455][2][Y0-0000000000000000] [lt=16] [dc=0] load file /sys/class/net/eth0/speed failed, rc -4000
```

**Comment by longdafeng** [comment]
Thanks for your feedback, we will fix this warning in the January version in 2022

**Comment by lichq3553** [comment]
It is expected warning message, because there is no /sys/class/net/$(NIC_IFNAME)/speed file in your environment. 
If you need to config network speed, you can manually create a config file as 'ob_work_dir/etc/nic.rate.config'. And you can edit the file and configure the speed in the file like: $(IF_NAME)=$(SPEED). 

For example, the file can be edited as "bond0=10000mb".

**Comment by lichangqing1234** [comment]
It is expected warning message, because there is no /sys/class/net/$(NIC_IFNAME)/speed file in your environment.
If you need to config network speed, you can manually create a config file as 'ob_work_dir/etc/nic.rate.config'. And you can edit the file and configure the speed in the file like: $(IF_NAME)=$(SPEED).

For example, the file can be edited as "bond0=10000mb".

**Comment by longdafeng** [comment]
在很多虚拟机下没有这个/sys/class/net/$(NIC_IFNAME)/speed  功能, 忽略掉
