### ISSUE TITLE
转储和合并的merge_action选项执行报错

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#729]
[参考官网](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/MERGE)

在sys租户下执行以下命令的时候报错。
alter system minor freeze table_id='1100611139453777';
alter system major freeze server='xxx:rpcport'; 
alter system start merge zone='zonex'' 

**麻烦帮忙确认一下merge_action这些选项是否在当前版本（3.1.1）下支持。**
     [tenant_list | replica | table_id ] [server_list] [zone_name]
    | START MERGE
      zone_name
    | {SUSPEND | RESUME} MERGE
      [zone_name]
    | CLEAN MERGE ERROR

**Comment by gaodg** [comment]
同问。
alter system minor freeze server='xxx:rpcport';
命令在企业版（3.1.2_20211125174627）和社区版（3.1.1）测试也是会报错。

**Comment by simonjoylet** [comment]
there are some bugs in the document. we will fix it as soon as possible.
1. the community edition of observer does not support `table_id` as a `minor freeze` option.
2. the grammar about `minor freeze` on server is lack of parenthesis. the correct grammar is `[SERVER [=] ('ip:port' [, 'ip:port'...])]`
3. we no longer support  the grammar of `START MERGE`.
4. you need `clear merge error` instead of `clean merge error`

**Comment by gaodg** [comment]
谢谢，测试没问题。
