### ISSUE TITLE
memstore里active数据量比total多

### ISSUE THREAD

**Issue by piuuuuuu** [oceanbase/oceanbase#85]
![image](https://user-images.githubusercontent.com/73813663/120974402-ac0b8e80-c7a2-11eb-8761-479359b4b31d.png)
在导入数据时，观察到gv$memstore里active的值比total多。
但是
![image](https://user-images.githubusercontent.com/73813663/120974591-e37a3b00-c7a2-11eb-82b5-decd72ca212f.png)

**Comment by nroskill** [comment]
There may be a uncommitted transaction in your environment, maybe your insert batch size is too large.

The reason of active memory > total memory is that the calculation of them are different.

Active memory = ( max_allocated_page_id - retired_page_id ) * PAGE_SIZE, PAGE_SIZE = 2M.
Total memory = sum(all_allocated_memory)
code ref
https://github.com/oceanbase/oceanbase/blob/master/src/share/allocator/ob_gmemstore_allocator.h

For example, there are 5 pages allocated, the first page is retired but not freed ( because of uncommitted transaction ), and the second, third page is freed.
In this case, total memory is (5 - 2) * 2M = 6M, active memory is 5 * 2M = 10M.

In most scence, active memory is less than total memory.
