### ISSUE TITLE
oceanbase::keybtree::MultibitSet::size

### ISSUE THREAD

**Issue by coding01000** [oceanbase/oceanbase#88]
>OB_INLINE int8_t size() const
  {
    return ATOMIC_LOAD((int16_t*)(&data_)) & ((1 << LEN_OF_COUNTER) - 1);
  }

>union {
    RawType data_; 
    uint8_t buf_[0]; 
    struct {
      uint8_t count_ : LEN_OF_COUNTER; 
      RawType pending_data_ : (LEN_OF_TOTAL_INDEX - LEN_OF_COUNTER); 
    };
  };

Why not return “count_” directly here?

**Comment by nroskill** [comment]
it's a good idea, but bit-field member can not use ATOMIC operation directly.

**Comment by coding01000** [comment]
> it's a good idea, but bit-field member can not use ATOMIC operation directly.

Thank you, I have another question，what does ”cal_index_“ do？
https://github.com/oceanbase/oceanbase/blob/179a540032a98f08b8db19047cc6b27274b15caf/src/storage/memtable/mvcc/ob_keybtree_deps.h#L160

**Comment by nroskill** [comment]
MultibitSet is a mini index for a btree leaf node, whose size is 64bit so that it can be updated by ATOMIC operation, and kv physical position in btree leaf node can be out of order. Out of order storage can avoid extra copy-on-write retry in multi-thread appending.
So in one word, MultibitSet recorded the real index of kv in one btree leaf node, and it is a inserting optimization method.
You can use at(0) to get the physical position of the smallest kv in one btree leaf, same principle for at(size() - 1) to the biggest one.
Back to your question, cal_index_ is just like ‘update’, it returned the MultibitSet after inserting value at index position.

**Comment by coding01000** [comment]
> MultibitSet is a mini index for a btree leaf node, whose size is 64bit so that it can be updated by ATOMIC operation, and kv physical position in btree leaf node can be out of order. Out of order storage can avoid extra copy-on-write retry in multi-thread appending.
> So in one word, MultibitSet recorded the real index of kv in one btree leaf node, and it is a inserting optimization method.
> You can use at(0) to get the physical position of the smallest kv in one btree leaf, same principle for at(size() - 1) to the biggest one.
> Back to your question, cal_index_ is just like ‘update’, it returned the MultibitSet after inserting value at index position.

Thank you for your patient answers
